logging:
  file:
    name: logs/github-anomalies.log

github:
  hours-diff: 3

scanners:
  delete-repo:
    min-minutes: 10
  push:
    forbidden-start-time: "14:00"
    forbidden-end-time: "16:00"
  create-team:
    invalid-prefixes: "hacker"

notify:
  log: true
  console: true
